### ISSUE TITLE
Morning Session Code Review

### ISSUE THREAD

**Issue by kelvinbush** [RWUBAKWANAYO/Portfolio-Setup#9]
> During our morning session review we found the following issues in your code:

- Please use semantics tag only ,they make your code better. On[ line 60](https://github.com/RWUBAKWANAYO/Portfolio-Setup/blob/d06a35c4a54826da98e177f8fd3bebbc25ebdb40/index.html#L60) it was not necessary to wrap the image with `<div>`.
- You could add labels to the `form input` and `textarea` elements.
- Please load or import only the fonts and font weights that you need.
- You could import your fonts once in either the `html head` tag or at the start of your `css` file, no need to import in both files.

**Comment by RWUBAKWANAYO** [comment]
Issues have been solved
